### PR TITLE
small pactch repatched

### PR DESCRIPTION
**Pull request by Mwallx**
Changelog(copied from #366, with a single addition): 
QOL: Gem Cannon now also Exhausts Gems from cards in Stasis, and gems in sockets now actually do go to the Exhaust pile.
QOL: Character Boss' Cards' beta art is now independantly togglable(Should cover most cards, report if any isn't functional).
QOL: Miscellaneous text and visual fix.
BALANCE: Unupgraded Prismatic Spray damage buffed: 2→3 for more initial pickability.
BALANCE: Upgraded Prismatic Barrier Block nerfed: 4→3 to counter the goodness of multi-dexterirty utilizability a bit.
BALANCE: Chrono-Boost buffed: (1 Strength) , 1 Strength per 12 cards played → (2 Strength) , 2 Strength per 12 cards played.
BUGFIX: Deflecting Bracer no longer functions when you're in Defensive Mode.
BUGFIX: Bottled Anomaly & Bottled Black Hole & Blank Card now functions like how the players would expect for Unknown cards.
BUGFIX Split: Specialist is now seeded.
BUGFIX: Fixes taking damage from the second tackle duplicated by Duplicated Form when you have Protective Gear.
BUGFIX: Fixed a rare bug where the game crashes if you play a Strike&Defend from characters other than the Bronze Automaton, which gained Encode in a previous Back to Basics event. (Fixing by only allowing adding Encoding to Automaton's Strikes and Defends)
BUGFIX: Fear No Evil now functions against Character Bosses.
BUGFIX: Ghost Lash & Specters Wail's Afterlife damage effect is now modified correctly by modifiers (like Vulnerable, Weak, Strength, Vigor).
BUGFIX: Fixed Character Bosses' energy panel popping up during an event before the fight starts (captive hero colosseum event).
BUGFIX: Fixed Act 3 Defect generating a Lightning Orb by Storm+Defragment with extra damage than it's supposed to.
BUGFIX: Fixed Woman in Blue's Intangible potion not functional to Non-attack damage.
OPTIMIZATION: Replaced an outdated image loading method to avoid potential memory issue.

### CODE REVIEW

**Comment by Stanek-K** [comment]
It would be nice if you provided a full list of changes, so it is easier to understand what is being changed.
 That said I checked all of what you did and some of the things you are trying to do need to be reversed:
-**Branch** and **Vigor**, current interaction is correct, changing would just create inconsistencies.
-Leave Hermit alone, we already have a lot of problems with updating him, and additional differences between standalone and Downfall will only complicate things further.
-Never solve anything by adding connections to mechanics into card abstracts, one of the things I want to do is to remove need for having an Abstract Card for each character, and what you did would just make that harder.

Btw AbstractBossCard now extends AbstractDownfallCard, so you can just use DM (or DM2) if you need additional magic numbers.

**Comment by Mwallx** [comment]
> 

It's not correct, vanilla doesn't have any Attack that does not deal damage,  we made one ourself which just happens to be an exception of how vigor nomally does. Nobody would be happy if you have 10 vigor, playing a card to get Block and the vigor is gone, the true correct way for Branch is this: make the option gives you a card, and make Branch an exhaust SKill, my current method is just a lazy way to achieve that.
 As for the hermit name change, it's a result I talked with Alex so you don't need to worry about that.
The new Abscard is used for enabling beta art on the bosses' cards, some of them are not vanilla cards, so I needed an extra way to deal with their IDs to make them work(Hermit cards and Downfall exclusive cards), if you could achieve that without the need of my added abs classes feel free to do your changes in the future.

**Comment by Stanek-K** [comment]
> > 
> It's not correct, vanilla doesn't have any Attack that does not deal damage,  we made one ourself which just happens to be an exception of how vigor nomally does. Nobody would be happy if you have 10 vigor, playing a card to get Block and the vigor is gone.

You say that, but there are multiple Attacks that don't deal damage if you don't fulfill the conditions: **Flechettes**, **Finisher**, **Barrage**, or just playing an X-Cost with no energy, to name a few, and they all consume Vigor when played.

**Comment by Mwallx** [comment]
> > > 
> > 
> > 
> > It's not correct, vanilla doesn't have any Attack that does not deal damage,  we made one ourself which just happens to be an exception of how vigor nomally does. Nobody would be happy if you have 10 vigor, playing a card to get Block and the vigor is gone.
> 
> You say that, but there are multiple Attacks that don't deal damage if you don't fulfill the conditions: **Flechettes**, **Finisher**, **Barrage**, or just playing an X-Cost with no energy, to name a few, and they all consume **Vigor** when played, the fact that an Attack didn't deal damage doesn't mean that it shouldn't consume **Vigor**.

Even so that's just a bug not fixed yet, there's no reason you add a mechanic which is supposed to increase Attack damage, but got consumed without achieving what it's supposed to achieve, it could be avoided by my method if you aren't happy with my lazy way I'll code the new way.

**Comment by Mwallx** [comment]
> > > 
> > 
> > 
> > It's not correct, vanilla doesn't have any Attack that does not deal damage,  we made one ourself which just happens to be an exception of how vigor nomally does. Nobody would be happy if you have 10 vigor, playing a card to get Block and the vigor is gone.
> 
> You say that, but there are multiple Attacks that don't deal damage if you don't fulfill the conditions: **Flechettes**, **Finisher**, **Barrage**, or just playing an X-Cost with no energy, to name a few, and they all consume **Vigor** when played, the fact that an Attack didn't deal damage doesn't mean that it shouldn't consume **Vigor**.
> 
> > ...the true correct way for Branch is this: make the option gives you a card and encodes the other, and make Branch an exhaust SKill...
> 
> Yeah, that would be ideal way to make the effect work, but description space doesn't allow for effect like that.

not really, make the options 2 preview cards, desc reads:" Chooses to gain a card from 2, encode the other card NL Exhaust."

**Comment by Stanek-K** [comment]
Are you seriously trying to say that the description that you are suggesting explains anything? I could rework the card to make it work, but it doesn't fit my plans, and I don't want to rework a card, as well as have to then revert said rework in the next Auto update. Sorry but that amount of work just isn't worth the effort to remove a slight inconvenience that would require a specific relic to even have a chance to happen.

**Comment by Mwallx** [comment]
> Are you seriously trying to say that the description that you are suggesting explains anything? I could rework the card to make it work, but it doesn't fit my plans, and I don't want to rework a card, as well as have to then revert said rework in the next Auto update. Sorry but that amount of work just isn't worth the effort to remove a slight inconvenience that would require a specific relic to even have a chance to happen.

fine I'll delete it.

**Pull request merged**
